name: Test

on: 
  pull_request:
    branches: 
      - master

jobs:
  whatever:
    name: trying to create message
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: step1
      run: |
        echo `grep -q "put" README.md`
        echo `grep -q "longRunningOperation:true" REAMDE.md`
        if [ `grep -q "put" README.md` ]
        then
          echo "here"
          grep -q "longRunningOperation:true" REAMDE.md
        fi
#        a=$(grep -q "put" README.md)
#        echo "$a"
#        b=$(grep -q "longRunningOperation:true" README.md)
#        echo "$b"
#        $a == $b
